language: node_js
node_js:
  - "8.10.0"

addons:
  chrome: stable
  sonarcloud:
    organization: "dev-saas"

cache:
  directories:
    - node_modules

services:
  - mongodb
  - redis-server

install:
  - npm install
  - npm run build_testing

script:
  - npm test

after_success:
  - sonar-scanner