export { default as AuthPage } from './Auth'
export { default as EventsPage } from './Events'
export { default as BookingsPage } from './Bookings'
export { default as RoomPage } from './Room'
export { default as ShopPage } from './Shop'
export { default as CartPage } from './Cart'
export { default as ConfirmationPage } from './Confirmation'
